import process from "node:process";
import { URL } from "node:url";
import { readFileSync, writeFileSync } from "node:fs";
const api = JSON.parse(
  readFileSync(new URL("../../../crates/topup/openapi.json", import.meta.url), "utf8"),
);
const root = process.argv[2]
  ? new URL(process.argv[2] + "/", `file://${process.cwd()}/`)
  : new URL("../src/", import.meta.url);
const camel = (s) => s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
const pascal = (s) => {
  const name = camel(s);
  return name[0].toUpperCase() + name.slice(1);
};
const resources = {};
const contracts = {};
let types =
  '// Generated by scripts/generate-server.mjs from OpenAPI; do not edit.\nimport type { components, operations } from "./generated/openapi.js";\n';
for (const name of Object.keys(api.components.schemas))
  types += `export type ${name} = components["schemas"]["${name}"];\n`;
const aliases = new Set(Object.keys(api.components.schemas));
const responseSchema = (op) =>
  Object.entries(op.responses).find(([status]) => /^2\d\d$/.test(status))[1].content[
    "application/json"
  ].schema;
for (const [path, methods] of Object.entries(api.paths))
  for (const [httpMethod, op] of Object.entries(methods)) {
    if (path === "/v1/attestation") continue;
    const resource = path.split("/")[2];
    const singleton = ["account", "payment_settings", "config", "balance"].includes(resource);
    const id = path.includes("{id}");
    const action = path.split("/")[id ? 4 : 3];
    let method = action
      ? camel(action)
      : httpMethod === "get"
        ? id || singleton
          ? "retrieve"
          : "listPage"
        : httpMethod === "delete"
          ? resource === "api_keys"
            ? "revoke"
            : "delete"
          : id || singleton
            ? "update"
            : "create";
    if (resource === "treasuries" && path.endsWith("/challenge")) method = "challenge";
    if (resource === "account" && action === "pause") method = "pauseQuotes";
    if (resource === "account" && action === "resume") method = "resumeQuotes";
    if (resource === "account" && action === "webhook_keys") method = "rollWebhookKey";
    const body = op.requestBody?.content["application/json"].schema;
    const query = (op.parameters ?? []).filter((p) => p.in === "query");
    const paramAlias = `${pascal({ deposit_addresses: "deposit_address", treasuries: "treasury" }[resource] ?? resource.replace(/s$/, ""))}${pascal(method === "listPage" ? "list" : method)}Params`;
    let paramType;
    if (body || query.length) {
      paramType = paramAlias;
      if (!aliases.has(paramAlias)) {
        aliases.add(paramAlias);
        types += `export type ${paramAlias} = ${body ? `operations["${op.operationId}"]["requestBody"]["content"]["application/json"]` : `NonNullable<operations["${op.operationId}"]["parameters"]["query"]>`};\n`;
      }
    }
    const response = responseSchema(op);
    const responseType = response.$ref?.split("/").at(-1);
    if (!responseType) throw Error(op.operationId);
    contracts[op.operationId] = { response, ...(body ? { body } : {}) };
    const parameters = [
      ...(id ? ["id: string"] : []),
      ...(paramType
        ? [`params${body ? "" : "?"}: Types.${paramType}`]
        : method === "retrieve" && id
          ? ["params?: undefined"]
          : []),
      "options?: RequestOptions",
    ].join(", ");
    const encodedPath = "`" + path.replace("{id}", "${encodeId(id)}") + "`";
    const implementation = `  ${method}(${parameters}): Promise<Types.${responseType}> {\n    return this.execute<Types.${responseType}>("${op.operationId}", "${httpMethod.toUpperCase()}", ${encodedPath}, ${paramType ? "params" : "undefined"}, options);\n  }\n`;
    resources[resource] ??= [];
    resources[resource].push(implementation);
    if (method === "listPage") {
      const item = api.components.schemas[responseType].properties.data.items.$ref
        .split("/")
        .at(-1);
      resources[resource].push(
        `  list(params: Types.${paramAlias} = {}, options?: RequestOptions): AsyncIterable<Types.${item}> {\n    return paginate((query) => this.listPage(query, options), params);\n  }\n`,
      );
    }
  }
let output =
  '// Generated by scripts/generate-server.mjs from OpenAPI; do not edit.\nimport type * as Types from "./types.js";\nimport type { RequestOptions } from "./transport.js";\nimport { encodeId, paginate, type Execute } from "./resource.js";\n';
for (const [name, methods] of Object.entries(resources))
  output += `export class ${pascal(name)}Resource {\n  constructor(private readonly execute: Execute) {}\n${methods.join("")} }\n`;
const prune = (value) => {
  if (Array.isArray(value)) return value.map(prune);
  if (value && typeof value === "object")
    return Object.fromEntries(
      Object.entries(value)
        .filter(([key]) =>
          [
            "$ref",
            "type",
            "required",
            "properties",
            "items",
            "oneOf",
            "anyOf",
            "minimum",
            "maximum",
            "additionalProperties",
          ].includes(key),
        )
        .map(([key, v]) => [
          key,
          key === "properties"
            ? Object.fromEntries(
                Object.entries(v).map(([k, x]) => [
                  k,
                  k === "object" && x.enum ? { ...prune(x), enum: x.enum } : prune(x),
                ]),
              )
            : prune(v),
        ]),
    );
  return value;
};
writeFileSync(new URL("types.ts", root), types);
writeFileSync(new URL("resources.ts", root), output);
writeFileSync(
  new URL("schemas.ts", root),
  '// Generated by scripts/generate-server.mjs from OpenAPI; do not edit.\nimport type { Schema, Contract } from "./validation.js";\nexport const schemas: Record<string, Schema> = ' +
    JSON.stringify(
      Object.fromEntries(Object.entries(api.components.schemas).map(([k, v]) => [k, prune(v)])),
      null,
      2,
    ) +
    ";\nexport const contracts: Record<string, Contract> = " +
    JSON.stringify(contracts, null, 2) +
    ";\n",
);
