// Generated by scripts/generate-server.mjs from OpenAPI; do not edit.
import type * as Types from "./types.js";
import type { RequestOptions } from "./transport.js";
import { encodeId, paginate, type Execute } from "./resource.js";
export class AccountResource {
  constructor(private readonly execute: Execute) {}
  retrieve(options?: RequestOptions): Promise<Types.AccountObject> {
    return this.execute<Types.AccountObject>("get_account", "GET", `/v1/account`, undefined, options);
  }
  pauseQuotes(params: Types.AccountPauseQuotesParams, options?: RequestOptions): Promise<Types.AccountObject> {
    return this.execute<Types.AccountObject>("pause_account", "POST", `/v1/account/pause`, params, options);
  }
  resumeQuotes(params: Types.AccountResumeQuotesParams, options?: RequestOptions): Promise<Types.AccountObject> {
    return this.execute<Types.AccountObject>("resume_account", "POST", `/v1/account/resume`, params, options);
  }
  rollWebhookKey(params: Types.AccountRollWebhookKeyParams, options?: RequestOptions): Promise<Types.AccountObject> {
    return this.execute<Types.AccountObject>("roll_webhook_key", "POST", `/v1/account/webhook_keys/roll`, params, options);
  }
 }
export class ApiKeysResource {
  constructor(private readonly execute: Execute) {}
  listPage(params?: Types.ApiKeyListParams, options?: RequestOptions): Promise<Types.ApiKeyList> {
    return this.execute<Types.ApiKeyList>("list_api_keys", "GET", `/v1/api_keys`, params, options);
  }
  list(params: Types.ApiKeyListParams = {}, options?: RequestOptions): AsyncIterable<Types.ApiKeyObject> {
    return paginate((query) => this.listPage(query, options), params);
  }
  create(params: Types.ApiKeyCreateParams, options?: RequestOptions): Promise<Types.ApiKeyObject> {
    return this.execute<Types.ApiKeyObject>("create_api_key", "POST", `/v1/api_keys`, params, options);
  }
  revoke(id: string, options?: RequestOptions): Promise<Types.ApiKeyObject> {
    return this.execute<Types.ApiKeyObject>("revoke_api_key", "DELETE", `/v1/api_keys/${encodeId(id)}`, undefined, options);
  }
  retrieve(id: string, params?: undefined, options?: RequestOptions): Promise<Types.ApiKeyObject> {
    return this.execute<Types.ApiKeyObject>("get_api_key", "GET", `/v1/api_keys/${encodeId(id)}`, undefined, options);
  }
  roll(id: string, params: Types.ApiKeyRollParams, options?: RequestOptions): Promise<Types.ApiKeyObject> {
    return this.execute<Types.ApiKeyObject>("roll_api_key", "POST", `/v1/api_keys/${encodeId(id)}/roll`, params, options);
  }
 }
export class BalanceResource {
  constructor(private readonly execute: Execute) {}
  retrieve(options?: RequestOptions): Promise<Types.Balance> {
    return this.execute<Types.Balance>("get_balance", "GET", `/v1/balance`, undefined, options);
  }
 }
export class ConfigResource {
  constructor(private readonly execute: Execute) {}
  retrieve(options?: RequestOptions): Promise<Types.Config> {
    return this.execute<Types.Config>("get_config", "GET", `/v1/config`, undefined, options);
  }
 }
export class DepositAddressesResource {
  constructor(private readonly execute: Execute) {}
  listPage(params?: Types.DepositAddressListParams, options?: RequestOptions): Promise<Types.DepositAddressList> {
    return this.execute<Types.DepositAddressList>("list_deposit_addresses", "GET", `/v1/deposit_addresses`, params, options);
  }
  list(params: Types.DepositAddressListParams = {}, options?: RequestOptions): AsyncIterable<Types.DepositAddress> {
    return paginate((query) => this.listPage(query, options), params);
  }
  create(params: Types.DepositAddressCreateParams, options?: RequestOptions): Promise<Types.DepositAddress> {
    return this.execute<Types.DepositAddress>("create_deposit_address", "POST", `/v1/deposit_addresses`, params, options);
  }
  retrieve(id: string, params?: Types.DepositAddressRetrieveParams, options?: RequestOptions): Promise<Types.DepositAddressView> {
    return this.execute<Types.DepositAddressView>("get_deposit_address", "GET", `/v1/deposit_addresses/${encodeId(id)}`, params, options);
  }
  update(id: string, params: Types.DepositAddressUpdateParams, options?: RequestOptions): Promise<Types.DepositAddress> {
    return this.execute<Types.DepositAddress>("update_deposit_address", "POST", `/v1/deposit_addresses/${encodeId(id)}`, params, options);
  }
  rotate(id: string, options?: RequestOptions): Promise<Types.DepositAddress> {
    return this.execute<Types.DepositAddress>("rotate_deposit_address", "POST", `/v1/deposit_addresses/${encodeId(id)}/rotate`, undefined, options);
  }
 }
export class DepositsResource {
  constructor(private readonly execute: Execute) {}
  listPage(params?: Types.DepositListParams, options?: RequestOptions): Promise<Types.DepositList> {
    return this.execute<Types.DepositList>("list_deposits", "GET", `/v1/deposits`, params, options);
  }
  list(params: Types.DepositListParams = {}, options?: RequestOptions): AsyncIterable<Types.Deposit> {
    return paginate((query) => this.listPage(query, options), params);
  }
  retrieve(id: string, params?: Types.DepositRetrieveParams, options?: RequestOptions): Promise<Types.Deposit> {
    return this.execute<Types.Deposit>("get_deposit", "GET", `/v1/deposits/${encodeId(id)}`, params, options);
  }
  update(id: string, params: Types.DepositUpdateParams, options?: RequestOptions): Promise<Types.Deposit> {
    return this.execute<Types.Deposit>("update_deposit", "POST", `/v1/deposits/${encodeId(id)}`, params, options);
  }
 }
export class EventsResource {
  constructor(private readonly execute: Execute) {}
  listPage(params?: Types.EventListParams, options?: RequestOptions): Promise<Types.EventList> {
    return this.execute<Types.EventList>("list_events", "GET", `/v1/events`, params, options);
  }
  list(params: Types.EventListParams = {}, options?: RequestOptions): AsyncIterable<Types.EventObjectResponse> {
    return paginate((query) => this.listPage(query, options), params);
  }
  retrieve(id: string, params?: undefined, options?: RequestOptions): Promise<Types.EventObjectResponse> {
    return this.execute<Types.EventObjectResponse>("get_event", "GET", `/v1/events/${encodeId(id)}`, undefined, options);
  }
  resend(id: string, params: Types.EventResendParams, options?: RequestOptions): Promise<Types.EventObjectResponse> {
    return this.execute<Types.EventObjectResponse>("resend_event", "POST", `/v1/events/${encodeId(id)}/resend`, params, options);
  }
 }
export class ForwardersResource {
  constructor(private readonly execute: Execute) {}
  listPage(params?: Types.ForwarderListParams, options?: RequestOptions): Promise<Types.ForwarderList> {
    return this.execute<Types.ForwarderList>("list_forwarders", "GET", `/v1/forwarders`, params, options);
  }
  list(params: Types.ForwarderListParams = {}, options?: RequestOptions): AsyncIterable<Types.Forwarder> {
    return paginate((query) => this.listPage(query, options), params);
  }
 }
export class PaymentSettingsResource {
  constructor(private readonly execute: Execute) {}
  retrieve(options?: RequestOptions): Promise<Types.PaymentSettingsObject> {
    return this.execute<Types.PaymentSettingsObject>("get_payment_settings", "GET", `/v1/payment_settings`, undefined, options);
  }
  update(params: Types.PaymentSettingUpdateParams, options?: RequestOptions): Promise<Types.PaymentSettingsObject> {
    return this.execute<Types.PaymentSettingsObject>("update_payment_settings", "POST", `/v1/payment_settings`, params, options);
  }
 }
export class QuotesResource {
  constructor(private readonly execute: Execute) {}
  listPage(params?: Types.QuoteListParams, options?: RequestOptions): Promise<Types.QuoteList> {
    return this.execute<Types.QuoteList>("list_quotes", "GET", `/v1/quotes`, params, options);
  }
  list(params: Types.QuoteListParams = {}, options?: RequestOptions): AsyncIterable<Types.Quote> {
    return paginate((query) => this.listPage(query, options), params);
  }
  create(params: Types.QuoteCreateParams, options?: RequestOptions): Promise<Types.Quote> {
    return this.execute<Types.Quote>("create_quote", "POST", `/v1/quotes`, params, options);
  }
  retrieve(id: string, params?: Types.QuoteRetrieveParams, options?: RequestOptions): Promise<Types.QuoteView> {
    return this.execute<Types.QuoteView>("get_quote", "GET", `/v1/quotes/${encodeId(id)}`, params, options);
  }
  update(id: string, params: Types.QuoteUpdateParams, options?: RequestOptions): Promise<Types.Quote> {
    return this.execute<Types.Quote>("update_quote", "POST", `/v1/quotes/${encodeId(id)}`, params, options);
  }
  cancel(id: string, options?: RequestOptions): Promise<Types.Quote> {
    return this.execute<Types.Quote>("cancel_quote", "POST", `/v1/quotes/${encodeId(id)}/cancel`, undefined, options);
  }
 }
export class RefundsResource {
  constructor(private readonly execute: Execute) {}
  listPage(params?: Types.RefundListParams, options?: RequestOptions): Promise<Types.RefundList> {
    return this.execute<Types.RefundList>("list_refunds", "GET", `/v1/refunds`, params, options);
  }
  list(params: Types.RefundListParams = {}, options?: RequestOptions): AsyncIterable<Types.Refund> {
    return paginate((query) => this.listPage(query, options), params);
  }
  create(params: Types.RefundCreateParams, options?: RequestOptions): Promise<Types.Refund> {
    return this.execute<Types.Refund>("create_refund", "POST", `/v1/refunds`, params, options);
  }
  retrieve(id: string, params?: Types.RefundRetrieveParams, options?: RequestOptions): Promise<Types.Refund> {
    return this.execute<Types.Refund>("get_refund", "GET", `/v1/refunds/${encodeId(id)}`, params, options);
  }
  update(id: string, params: Types.RefundUpdateParams, options?: RequestOptions): Promise<Types.Refund> {
    return this.execute<Types.Refund>("update_refund", "POST", `/v1/refunds/${encodeId(id)}`, params, options);
  }
  cancel(id: string, options?: RequestOptions): Promise<Types.Refund> {
    return this.execute<Types.Refund>("cancel_refund", "POST", `/v1/refunds/${encodeId(id)}/cancel`, undefined, options);
  }
  markPaid(id: string, params: Types.RefundMarkPaidParams, options?: RequestOptions): Promise<Types.Refund> {
    return this.execute<Types.Refund>("mark_refund_paid", "POST", `/v1/refunds/${encodeId(id)}/mark_paid`, params, options);
  }
 }
export class SweepsResource {
  constructor(private readonly execute: Execute) {}
  listPage(params?: Types.SweepListParams, options?: RequestOptions): Promise<Types.SweepList> {
    return this.execute<Types.SweepList>("list_sweeps", "GET", `/v1/sweeps`, params, options);
  }
  list(params: Types.SweepListParams = {}, options?: RequestOptions): AsyncIterable<Types.Sweep> {
    return paginate((query) => this.listPage(query, options), params);
  }
 }
export class TreasuriesResource {
  constructor(private readonly execute: Execute) {}
  listPage(params?: Types.TreasuryListParams, options?: RequestOptions): Promise<Types.TreasuryList> {
    return this.execute<Types.TreasuryList>("list_treasuries", "GET", `/v1/treasuries`, params, options);
  }
  list(params: Types.TreasuryListParams = {}, options?: RequestOptions): AsyncIterable<Types.Treasury> {
    return paginate((query) => this.listPage(query, options), params);
  }
  create(params: Types.TreasuryCreateParams, options?: RequestOptions): Promise<Types.Treasury> {
    return this.execute<Types.Treasury>("create_treasury", "POST", `/v1/treasuries`, params, options);
  }
  challenge(params: Types.TreasuryChallengeParams, options?: RequestOptions): Promise<Types.TreasuryChallenge> {
    return this.execute<Types.TreasuryChallenge>("create_treasury_challenge", "POST", `/v1/treasuries/challenge`, params, options);
  }
  retrieve(id: string, params?: undefined, options?: RequestOptions): Promise<Types.Treasury> {
    return this.execute<Types.Treasury>("get_treasury", "GET", `/v1/treasuries/${encodeId(id)}`, undefined, options);
  }
  cancel(id: string, options?: RequestOptions): Promise<Types.Treasury> {
    return this.execute<Types.Treasury>("cancel_treasury", "POST", `/v1/treasuries/${encodeId(id)}/cancel`, undefined, options);
  }
  pause(id: string, options?: RequestOptions): Promise<Types.Treasury> {
    return this.execute<Types.Treasury>("pause_treasury", "POST", `/v1/treasuries/${encodeId(id)}/pause`, undefined, options);
  }
  resume(id: string, options?: RequestOptions): Promise<Types.Treasury> {
    return this.execute<Types.Treasury>("resume_treasury", "POST", `/v1/treasuries/${encodeId(id)}/resume`, undefined, options);
  }
 }
export class WebhookEndpointsResource {
  constructor(private readonly execute: Execute) {}
  listPage(params?: Types.WebhookEndpointListParams, options?: RequestOptions): Promise<Types.WebhookEndpointList> {
    return this.execute<Types.WebhookEndpointList>("list_webhook_endpoints", "GET", `/v1/webhook_endpoints`, params, options);
  }
  list(params: Types.WebhookEndpointListParams = {}, options?: RequestOptions): AsyncIterable<Types.WebhookEndpointObject> {
    return paginate((query) => this.listPage(query, options), params);
  }
  create(params: Types.WebhookEndpointCreateParams, options?: RequestOptions): Promise<Types.WebhookEndpointObject> {
    return this.execute<Types.WebhookEndpointObject>("create_webhook_endpoint", "POST", `/v1/webhook_endpoints`, params, options);
  }
  delete(id: string, options?: RequestOptions): Promise<Types.DeletedWebhookEndpoint> {
    return this.execute<Types.DeletedWebhookEndpoint>("delete_webhook_endpoint", "DELETE", `/v1/webhook_endpoints/${encodeId(id)}`, undefined, options);
  }
  retrieve(id: string, params?: undefined, options?: RequestOptions): Promise<Types.WebhookEndpointObject> {
    return this.execute<Types.WebhookEndpointObject>("get_webhook_endpoint", "GET", `/v1/webhook_endpoints/${encodeId(id)}`, undefined, options);
  }
  update(id: string, params: Types.WebhookEndpointUpdateParams, options?: RequestOptions): Promise<Types.WebhookEndpointObject> {
    return this.execute<Types.WebhookEndpointObject>("update_webhook_endpoint", "POST", `/v1/webhook_endpoints/${encodeId(id)}`, params, options);
  }
  test(id: string, options?: RequestOptions): Promise<Types.EventObjectResponse> {
    return this.execute<Types.EventObjectResponse>("test_webhook_endpoint", "POST", `/v1/webhook_endpoints/${encodeId(id)}/test`, undefined, options);
  }
 }
