// Generated by scripts/generate-server.mjs from OpenAPI; do not edit.
import type { Schema, Contract } from "./validation.js";
export const schemas: Record<string, Schema> = {
  "AccountObject": {
    "properties": {
      "charges_enabled": {
        "type": "boolean"
      },
      "created": {
        "type": "integer"
      },
      "id": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "name": {
        "type": "string"
      },
      "object": {
        "type": "string",
        "enum": [
          "account"
        ]
      },
      "paused_scopes": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "webhook_keys": {
        "items": {
          "$ref": "#/components/schemas/WebhookKeyVersion"
        },
        "type": "array"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "name",
      "charges_enabled",
      "paused_scopes",
      "webhook_keys",
      "created"
    ],
    "type": "object"
  },
  "AccountSelfPauseRequest": {
    "additionalProperties": false,
    "properties": {
      "scopes": {
        "items": {
          "type": "string"
        },
        "type": "array"
      }
    },
    "required": [
      "scopes"
    ],
    "type": "object"
  },
  "ApiKeyList": {
    "properties": {
      "data": {
        "items": {
          "$ref": "#/components/schemas/ApiKeyObject"
        },
        "type": "array"
      },
      "has_more": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "list"
        ]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "object",
      "url",
      "has_more",
      "data"
    ],
    "type": "object"
  },
  "ApiKeyObject": {
    "properties": {
      "created": {
        "type": "integer"
      },
      "expires_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "id": {
        "type": "string"
      },
      "last_used": {
        "type": [
          "integer",
          "null"
        ]
      },
      "livemode": {
        "type": "boolean"
      },
      "name": {
        "type": "string"
      },
      "object": {
        "type": "string",
        "enum": [
          "api_key"
        ]
      },
      "permissions": {
        "items": {
          "type": "string"
        },
        "type": [
          "array",
          "null"
        ]
      },
      "redacted": {
        "type": "string"
      },
      "secret": {
        "type": [
          "string",
          "null"
        ]
      },
      "status": {
        "type": "string"
      },
      "type": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "type",
      "name",
      "redacted",
      "status",
      "created"
    ],
    "type": "object"
  },
  "AttestationResponse": {
    "properties": {
      "account": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "attestation"
        ]
      },
      "report_data": {
        "type": "string"
      },
      "tdx_quote": {
        "type": "string"
      },
      "webhook_keys": {
        "items": {
          "$ref": "#/components/schemas/WebhookKeyObject"
        },
        "type": "array"
      }
    },
    "required": [
      "object",
      "account",
      "livemode",
      "webhook_keys",
      "report_data",
      "tdx_quote"
    ],
    "type": "object"
  },
  "AvailableAsset": {
    "properties": {
      "accepted": {
        "type": "boolean"
      },
      "asset": {
        "type": "string"
      },
      "contract": {
        "type": "string"
      },
      "decimals": {
        "minimum": 0,
        "type": "integer"
      },
      "enabled": {
        "type": "boolean"
      },
      "max_deposit_atomic": {
        "$ref": "#/components/schemas/BoundsAtomic"
      },
      "min_amount": {
        "$ref": "#/components/schemas/BoundsU64"
      },
      "min_deposit_atomic": {
        "$ref": "#/components/schemas/BoundsAtomic"
      },
      "min_refund_atomic": {
        "$ref": "#/components/schemas/BoundsAtomic"
      },
      "pricing": {
        "type": "string"
      },
      "quote_amount_decimals": {
        "minimum": 0,
        "type": "integer"
      },
      "quote_spread_bps": {
        "$ref": "#/components/schemas/BoundsU64"
      },
      "quote_tolerance_bps": {
        "$ref": "#/components/schemas/BoundsU64"
      },
      "quote_ttl_seconds": {
        "$ref": "#/components/schemas/BoundsU64"
      }
    },
    "required": [
      "asset",
      "contract",
      "decimals",
      "pricing",
      "quote_amount_decimals",
      "accepted",
      "enabled",
      "quote_ttl_seconds",
      "quote_spread_bps",
      "quote_tolerance_bps",
      "min_amount",
      "min_deposit_atomic",
      "max_deposit_atomic",
      "min_refund_atomic"
    ],
    "type": "object"
  },
  "AvailableChain": {
    "properties": {
      "assets": {
        "items": {
          "$ref": "#/components/schemas/AvailableAsset"
        },
        "type": "array"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "confirmations": {
        "$ref": "#/components/schemas/AvailableConfirmations"
      },
      "status": {
        "type": "string"
      }
    },
    "required": [
      "chain_id",
      "status",
      "confirmations",
      "assets"
    ],
    "type": "object"
  },
  "AvailableConfirmations": {
    "properties": {
      "default": {
        "type": "string"
      },
      "floor": {
        "type": "string"
      }
    },
    "required": [
      "floor",
      "default"
    ],
    "type": "object"
  },
  "Balance": {
    "properties": {
      "livemode": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "balance"
        ]
      },
      "unswept": {
        "items": {
          "$ref": "#/components/schemas/BalanceAmount"
        },
        "type": "array"
      }
    },
    "required": [
      "object",
      "livemode",
      "unswept"
    ],
    "type": "object"
  },
  "BalanceAmount": {
    "properties": {
      "amount_atomic": {
        "type": "string"
      },
      "asset": {
        "type": [
          "string",
          "null"
        ]
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "final_amount_atomic": {
        "type": "string"
      },
      "token": {
        "type": "string"
      }
    },
    "required": [
      "chain_id",
      "token",
      "amount_atomic",
      "final_amount_atomic"
    ],
    "type": "object"
  },
  "BoundsAtomic": {
    "properties": {
      "default": {
        "type": "string"
      },
      "max": {
        "type": "string"
      },
      "min": {
        "type": "string"
      }
    },
    "required": [
      "default",
      "min",
      "max"
    ],
    "type": "object"
  },
  "BoundsU64": {
    "properties": {
      "default": {
        "minimum": 0,
        "type": "integer"
      },
      "max": {
        "minimum": 0,
        "type": "integer"
      },
      "min": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "default",
      "min",
      "max"
    ],
    "type": "object"
  },
  "ClientDepositAddress": {
    "properties": {
      "address": {
        "type": [
          "string",
          "null"
        ]
      },
      "id": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "networks": {
        "items": {
          "$ref": "#/components/schemas/ClientDepositAddressNetwork"
        },
        "type": "array"
      },
      "object": {
        "type": "string",
        "enum": [
          "deposit_address"
        ]
      },
      "payments": {
        "items": {
          "$ref": "#/components/schemas/ClientDepositAddressPayment"
        },
        "type": "array"
      },
      "status": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "status",
      "networks",
      "payments"
    ],
    "type": "object"
  },
  "ClientDepositAddressNetwork": {
    "properties": {
      "address": {
        "type": "string"
      },
      "assets": {
        "items": {
          "$ref": "#/components/schemas/DepositAddressAsset"
        },
        "type": "array"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "typical_credit_seconds": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "chain_id",
      "address",
      "assets",
      "typical_credit_seconds"
    ],
    "type": "object"
  },
  "ClientDepositAddressPayment": {
    "properties": {
      "amount_atomic": {
        "type": "string"
      },
      "asset": {
        "type": [
          "string",
          "null"
        ]
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "confirmations": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "created": {
        "type": "integer"
      },
      "decimals": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "status": {
        "type": "string"
      },
      "tx_hash": {
        "type": "string"
      }
    },
    "required": [
      "status",
      "chain_id",
      "amount_atomic",
      "tx_hash",
      "confirmations",
      "created"
    ],
    "type": "object"
  },
  "ClientQuote": {
    "properties": {
      "address": {
        "type": "string"
      },
      "amount": {
        "minimum": 0,
        "type": "integer"
      },
      "amount_atomic": {
        "type": "string"
      },
      "amount_credited": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "asset": {
        "type": "string"
      },
      "cancel_requested_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "confirmations": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "currency": {
        "type": "string"
      },
      "decimals": {
        "minimum": 0,
        "type": "integer"
      },
      "expires_at": {
        "type": "integer"
      },
      "id": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "quote"
        ]
      },
      "payment_status": {
        "type": "string"
      },
      "payment_uri": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "typical_credit_seconds": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "status",
      "amount",
      "currency",
      "asset",
      "decimals",
      "chain_id",
      "amount_atomic",
      "address",
      "payment_uri",
      "expires_at",
      "payment_status",
      "confirmations",
      "amount_credited",
      "typical_credit_seconds"
    ],
    "type": "object"
  },
  "Config": {
    "properties": {
      "assets": {
        "items": {
          "$ref": "#/components/schemas/ConfigAsset"
        },
        "type": "array"
      },
      "currency": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "max_open_amount_per_account": {
        "minimum": 0,
        "type": "integer"
      },
      "max_open_amount_per_customer": {
        "minimum": 0,
        "type": "integer"
      },
      "max_open_quotes": {
        "minimum": 0,
        "type": "integer"
      },
      "object": {
        "type": "string",
        "enum": [
          "config"
        ]
      },
      "quote_creations_per_customer_per_minute": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "object",
      "livemode",
      "currency",
      "max_open_quotes",
      "max_open_amount_per_account",
      "max_open_amount_per_customer",
      "quote_creations_per_customer_per_minute",
      "assets"
    ],
    "type": "object"
  },
  "ConfigAsset": {
    "properties": {
      "asset": {
        "type": "string"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "confirmations": {
        "type": "string"
      },
      "contract": {
        "type": "string"
      },
      "decimals": {
        "minimum": 0,
        "type": "integer"
      },
      "max_deposit_atomic": {
        "type": "string"
      },
      "min_amount": {
        "minimum": 0,
        "type": "integer"
      },
      "min_deposit_atomic": {
        "type": "string"
      },
      "min_refund_atomic": {
        "type": "string"
      },
      "pricing": {
        "type": "string"
      },
      "quote_amount_decimals": {
        "minimum": 0,
        "type": "integer"
      },
      "quote_spread_bps": {
        "minimum": 0,
        "type": "integer"
      },
      "quote_tolerance_bps": {
        "minimum": 0,
        "type": "integer"
      },
      "quote_ttl_seconds": {
        "minimum": 0,
        "type": "integer"
      },
      "typical_credit_seconds": {
        "minimum": 0,
        "type": "integer"
      },
      "typical_finality_seconds": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "chain_id",
      "asset",
      "contract",
      "decimals",
      "pricing",
      "min_amount",
      "min_deposit_atomic",
      "max_deposit_atomic",
      "min_refund_atomic",
      "quote_ttl_seconds",
      "quote_spread_bps",
      "quote_tolerance_bps",
      "quote_amount_decimals",
      "confirmations",
      "typical_credit_seconds",
      "typical_finality_seconds"
    ],
    "type": "object"
  },
  "CreateApiKeyRequest": {
    "additionalProperties": false,
    "properties": {
      "name": {
        "type": "string"
      },
      "permissions": {
        "items": {
          "type": "string"
        },
        "type": [
          "array",
          "null"
        ]
      },
      "type": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "type": "object"
  },
  "CreateDepositAddressRequest": {
    "additionalProperties": false,
    "properties": {
      "client_reference_id": {
        "type": "string"
      },
      "metadata": {
        "$ref": "#/components/schemas/MetadataParam"
      }
    },
    "required": [
      "client_reference_id"
    ],
    "type": "object"
  },
  "CreateQuoteRequest": {
    "additionalProperties": false,
    "properties": {
      "amount": {
        "minimum": 0,
        "type": "integer"
      },
      "asset": {
        "type": "string"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "client_reference_id": {
        "type": "string"
      },
      "currency": {
        "type": "string"
      },
      "metadata": {
        "$ref": "#/components/schemas/MetadataParam"
      }
    },
    "required": [
      "client_reference_id",
      "amount",
      "currency",
      "chain_id",
      "asset"
    ],
    "type": "object"
  },
  "CreateRefundRequest": {
    "additionalProperties": false,
    "properties": {
      "amount_atomic": {
        "type": [
          "string",
          "null"
        ]
      },
      "deposit": {
        "type": "string"
      },
      "destination_address": {
        "type": "string"
      },
      "metadata": {
        "$ref": "#/components/schemas/MetadataParam"
      }
    },
    "required": [
      "deposit",
      "destination_address"
    ],
    "type": "object"
  },
  "CreateTreasuryChallengeRequest": {
    "additionalProperties": false,
    "properties": {
      "address": {
        "type": "string"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "chain_id",
      "address"
    ],
    "type": "object"
  },
  "CreateTreasuryRequest": {
    "additionalProperties": false,
    "properties": {
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "message": {
        "type": "string"
      },
      "signature": {
        "type": "string"
      }
    },
    "required": [
      "chain_id",
      "message",
      "signature"
    ],
    "type": "object"
  },
  "CreateWebhookEndpointRequest": {
    "additionalProperties": false,
    "properties": {
      "description": {
        "type": [
          "string",
          "null"
        ]
      },
      "enabled_events": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "metadata": {
        "$ref": "#/components/schemas/MetadataParam"
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "url",
      "enabled_events"
    ],
    "type": "object"
  },
  "DeletedWebhookEndpoint": {
    "properties": {
      "deleted": {
        "type": "boolean"
      },
      "id": {
        "type": "string"
      },
      "object": {
        "type": "string",
        "enum": [
          "webhook_endpoint"
        ]
      }
    },
    "required": [
      "id",
      "object",
      "deleted"
    ],
    "type": "object"
  },
  "DeliveryAttempt": {
    "properties": {
      "at": {
        "type": "integer"
      },
      "status_code": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      }
    },
    "required": [
      "at"
    ],
    "type": "object"
  },
  "Deposit": {
    "properties": {
      "address": {
        "type": "string"
      },
      "admin": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/DepositAdmin"
          },
          {
            "type": "null"
          }
        ]
      },
      "amount": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "amount_atomic": {
        "type": "string"
      },
      "amount_refunded": {
        "minimum": 0,
        "type": "integer"
      },
      "amount_refunded_atomic": {
        "type": "string"
      },
      "amount_reversed": {
        "minimum": 0,
        "type": "integer"
      },
      "asset": {
        "type": [
          "string",
          "null"
        ]
      },
      "asset_contract": {
        "type": "string"
      },
      "block_hash": {
        "type": "string"
      },
      "block_number": {
        "minimum": 0,
        "type": "integer"
      },
      "block_time": {
        "type": "integer"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "client_reference_id": {
        "type": "string"
      },
      "created": {
        "type": "integer"
      },
      "currency": {
        "type": "string"
      },
      "deposit_address": {
        "type": [
          "string",
          "null"
        ]
      },
      "exchange_rate": {
        "type": [
          "string",
          "null"
        ]
      },
      "final": {
        "type": "boolean"
      },
      "final_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "from_address": {
        "type": "string"
      },
      "id": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "log_index": {
        "minimum": 0,
        "type": "integer"
      },
      "metadata": {
        "additionalProperties": {
          "type": "string"
        },
        "type": "object"
      },
      "object": {
        "type": "string",
        "enum": [
          "deposit"
        ]
      },
      "price_source": {
        "type": [
          "string",
          "null"
        ]
      },
      "quote": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/ExpandableQuote"
          },
          {
            "type": "null"
          }
        ]
      },
      "receipt_log_index": {
        "minimum": 0,
        "type": "integer"
      },
      "refunded": {
        "type": "boolean"
      },
      "rejection_reason": {
        "type": [
          "string",
          "null"
        ]
      },
      "replaced_by": {
        "type": [
          "string",
          "null"
        ]
      },
      "replaces": {
        "type": [
          "string",
          "null"
        ]
      },
      "revision": {
        "minimum": 0,
        "type": "integer"
      },
      "status": {
        "type": "string"
      },
      "swept": {
        "type": "boolean"
      },
      "tx_hash": {
        "type": "string"
      },
      "valued_at": {
        "type": [
          "integer",
          "null"
        ]
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "client_reference_id",
      "status",
      "final",
      "swept",
      "chain_id",
      "asset_contract",
      "amount_atomic",
      "currency",
      "address",
      "from_address",
      "tx_hash",
      "receipt_log_index",
      "revision",
      "log_index",
      "block_number",
      "block_hash",
      "block_time",
      "amount_refunded_atomic",
      "refunded",
      "amount_refunded",
      "amount_reversed",
      "created",
      "metadata"
    ],
    "type": "object"
  },
  "DepositAddress": {
    "properties": {
      "address": {
        "type": [
          "string",
          "null"
        ]
      },
      "client_reference_id": {
        "type": "string"
      },
      "client_secret": {
        "type": [
          "string",
          "null"
        ]
      },
      "created": {
        "type": "integer"
      },
      "id": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "metadata": {
        "additionalProperties": {
          "type": "string"
        },
        "type": "object"
      },
      "networks": {
        "items": {
          "$ref": "#/components/schemas/DepositAddressNetwork"
        },
        "type": "array"
      },
      "object": {
        "type": "string",
        "enum": [
          "deposit_address"
        ]
      },
      "payments": {
        "items": {
          "$ref": "#/components/schemas/Payment"
        },
        "type": "array"
      },
      "retired_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "salt": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "version": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "client_reference_id",
      "version",
      "salt",
      "status",
      "created",
      "metadata",
      "networks",
      "payments"
    ],
    "type": "object"
  },
  "DepositAddressAsset": {
    "properties": {
      "asset": {
        "type": "string"
      },
      "contract": {
        "type": "string"
      },
      "decimals": {
        "minimum": 0,
        "type": "integer"
      },
      "payment_uri": {
        "type": "string"
      }
    },
    "required": [
      "asset",
      "contract",
      "decimals",
      "payment_uri"
    ],
    "type": "object"
  },
  "DepositAddressList": {
    "properties": {
      "data": {
        "items": {
          "$ref": "#/components/schemas/DepositAddress"
        },
        "type": "array"
      },
      "has_more": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "list"
        ]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "object",
      "url",
      "has_more",
      "data"
    ],
    "type": "object"
  },
  "DepositAddressNetwork": {
    "properties": {
      "address": {
        "type": "string"
      },
      "assets": {
        "items": {
          "$ref": "#/components/schemas/DepositAddressAsset"
        },
        "type": "array"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "treasury": {
        "type": "string"
      }
    },
    "required": [
      "chain_id",
      "address",
      "treasury",
      "assets"
    ],
    "type": "object"
  },
  "DepositAddressView": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/DepositAddress"
      },
      {
        "$ref": "#/components/schemas/ClientDepositAddress"
      }
    ]
  },
  "DepositAdmin": {
    "properties": {
      "account": {
        "type": "string"
      },
      "block_time": {
        "type": "string"
      },
      "events": {
        "items": {
          "$ref": "#/components/schemas/DepositEventDelivery"
        },
        "type": "array"
      },
      "final_at": {
        "type": [
          "string",
          "null"
        ]
      },
      "price_scaled": {
        "type": [
          "string",
          "null"
        ]
      },
      "receipt_log_index": {
        "minimum": 0,
        "type": "integer"
      },
      "route": {
        "type": [
          "string",
          "null"
        ]
      },
      "route_version": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "settings_hold": {
        "type": [
          "string",
          "null"
        ]
      },
      "settings_revision": {
        "type": [
          "string",
          "null"
        ]
      },
      "state": {
        "type": "string"
      },
      "transitions": {
        "items": {
          "$ref": "#/components/schemas/DepositTransition"
        },
        "type": "array"
      },
      "updated_at": {
        "type": "string"
      }
    },
    "required": [
      "account",
      "state",
      "receipt_log_index",
      "block_time",
      "updated_at",
      "transitions",
      "events"
    ],
    "type": "object"
  },
  "DepositEventDelivery": {
    "properties": {
      "created_at": {
        "type": "string"
      },
      "delivered_at": {
        "type": [
          "string",
          "null"
        ]
      },
      "id": {
        "type": "string"
      },
      "type": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "type",
      "created_at"
    ],
    "type": "object"
  },
  "DepositList": {
    "properties": {
      "data": {
        "items": {
          "$ref": "#/components/schemas/Deposit"
        },
        "type": "array"
      },
      "has_more": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "list"
        ]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "object",
      "url",
      "has_more",
      "data"
    ],
    "type": "object"
  },
  "DepositTransition": {
    "properties": {
      "attempt": {
        "type": "integer"
      },
      "created_at": {
        "type": "string"
      },
      "evidence": {},
      "from_state": {
        "type": "string"
      },
      "id": {
        "type": "string"
      },
      "to_state": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "from_state",
      "to_state",
      "attempt",
      "evidence",
      "created_at"
    ],
    "type": "object"
  },
  "ErrorDetail": {
    "properties": {
      "code": {
        "type": "string"
      },
      "doc_url": {
        "type": "string"
      },
      "message": {
        "type": "string"
      },
      "param": {
        "type": [
          "string",
          "null"
        ]
      },
      "type": {
        "$ref": "#/components/schemas/ErrorType"
      }
    },
    "required": [
      "type",
      "code",
      "message"
    ],
    "type": "object"
  },
  "ErrorResponse": {
    "properties": {
      "error": {
        "$ref": "#/components/schemas/ErrorDetail"
      }
    },
    "required": [
      "error"
    ],
    "type": "object"
  },
  "ErrorType": {
    "type": "string"
  },
  "EventData": {
    "properties": {
      "object": {
        "type": "object"
      },
      "previous_attributes": {
        "type": [
          "object",
          "null"
        ]
      }
    },
    "required": [
      "object"
    ],
    "type": "object"
  },
  "EventList": {
    "properties": {
      "data": {
        "items": {
          "$ref": "#/components/schemas/EventObjectResponse"
        },
        "type": "array"
      },
      "has_more": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "list"
        ]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "object",
      "url",
      "has_more",
      "data"
    ],
    "type": "object"
  },
  "EventObjectResponse": {
    "properties": {
      "account": {
        "type": "string"
      },
      "actor": {
        "type": "string"
      },
      "created": {
        "type": "integer"
      },
      "data": {
        "$ref": "#/components/schemas/EventData"
      },
      "id": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "event"
        ]
      },
      "pending_webhooks": {
        "type": "integer"
      },
      "request": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/EventRequest"
          },
          {
            "type": "null"
          }
        ]
      },
      "type": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "object",
      "account",
      "livemode",
      "type",
      "created",
      "actor",
      "data",
      "pending_webhooks"
    ],
    "type": "object"
  },
  "EventRequest": {
    "properties": {
      "id": {
        "type": "string"
      },
      "idempotency_key": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "required": [
      "id"
    ],
    "type": "object"
  },
  "ExpandableDeposit": {
    "oneOf": [
      {
        "type": "string"
      },
      {
        "$ref": "#/components/schemas/Deposit"
      }
    ]
  },
  "ExpandableQuote": {
    "oneOf": [
      {
        "type": "string"
      },
      {
        "$ref": "#/components/schemas/Quote"
      }
    ]
  },
  "Forwarder": {
    "properties": {
      "address": {
        "type": "string"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "deposit_address": {
        "type": [
          "string",
          "null"
        ]
      },
      "factory": {
        "type": "string"
      },
      "id": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "forwarder"
        ]
      },
      "quote": {
        "type": [
          "string",
          "null"
        ]
      },
      "salt": {
        "type": "string"
      },
      "superseded_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "treasury": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "chain_id",
      "address",
      "factory",
      "salt",
      "treasury"
    ],
    "type": "object"
  },
  "ForwarderList": {
    "properties": {
      "data": {
        "items": {
          "$ref": "#/components/schemas/Forwarder"
        },
        "type": "array"
      },
      "has_more": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "list"
        ]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "object",
      "url",
      "has_more",
      "data"
    ],
    "type": "object"
  },
  "KnownErrorCode": {
    "type": "string"
  },
  "MarkRefundPaidRequest": {
    "additionalProperties": false,
    "properties": {
      "receipt_log_index": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "transaction_hash": {
        "type": "string"
      }
    },
    "required": [
      "transaction_hash"
    ],
    "type": "object"
  },
  "MetadataClear": {
    "type": "string"
  },
  "MetadataParam": {
    "oneOf": [
      {
        "additionalProperties": {
          "type": "string"
        },
        "type": "object"
      },
      {
        "$ref": "#/components/schemas/MetadataClear"
      }
    ]
  },
  "Payment": {
    "properties": {
      "amount_atomic": {
        "type": "string"
      },
      "asset": {
        "type": [
          "string",
          "null"
        ]
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "confirmations": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "deposit": {
        "type": "string"
      },
      "estimated_final_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "matches_quote": {
        "type": [
          "boolean",
          "null"
        ]
      },
      "status": {
        "type": "string"
      },
      "tx_hash": {
        "type": "string"
      }
    },
    "required": [
      "status",
      "chain_id",
      "tx_hash",
      "amount_atomic",
      "deposit"
    ],
    "type": "object"
  },
  "PaymentSettingsAsset": {
    "additionalProperties": false,
    "properties": {
      "asset": {
        "type": "string"
      },
      "max_deposit_atomic": {
        "type": [
          "string",
          "null"
        ]
      },
      "min_amount": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "min_deposit_atomic": {
        "type": [
          "string",
          "null"
        ]
      },
      "min_refund_atomic": {
        "type": [
          "string",
          "null"
        ]
      },
      "quote_spread_bps": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "quote_tolerance_bps": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "quote_ttl_seconds": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      }
    },
    "required": [
      "asset"
    ],
    "type": "object"
  },
  "PaymentSettingsChain": {
    "additionalProperties": false,
    "properties": {
      "assets": {
        "items": {
          "$ref": "#/components/schemas/PaymentSettingsAsset"
        },
        "type": "array"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "confirmations": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "required": [
      "chain_id",
      "assets"
    ],
    "type": "object"
  },
  "PaymentSettingsObject": {
    "properties": {
      "available": {
        "items": {
          "$ref": "#/components/schemas/AvailableChain"
        },
        "type": "array"
      },
      "chains": {
        "items": {
          "$ref": "#/components/schemas/PaymentSettingsChain"
        },
        "type": "array"
      },
      "livemode": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "payment_settings"
        ]
      },
      "quote_creations_per_customer_per_minute": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "revision": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "updated": {
        "type": "integer"
      }
    },
    "required": [
      "object",
      "livemode",
      "status",
      "revision",
      "updated",
      "quote_creations_per_customer_per_minute",
      "chains",
      "available"
    ],
    "type": "object"
  },
  "Quote": {
    "properties": {
      "address": {
        "type": "string"
      },
      "amount": {
        "minimum": 0,
        "type": "integer"
      },
      "amount_atomic": {
        "type": "string"
      },
      "asset": {
        "type": "string"
      },
      "cancel_requested_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "client_reference_id": {
        "type": "string"
      },
      "client_secret": {
        "type": [
          "string",
          "null"
        ]
      },
      "created": {
        "type": "integer"
      },
      "currency": {
        "type": "string"
      },
      "deposit": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/ExpandableDeposit"
          },
          {
            "type": "null"
          }
        ]
      },
      "exchange_rate": {
        "type": "string"
      },
      "expires_at": {
        "type": "integer"
      },
      "id": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "metadata": {
        "additionalProperties": {
          "type": "string"
        },
        "type": "object"
      },
      "object": {
        "type": "string",
        "enum": [
          "quote"
        ]
      },
      "payment": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/Payment"
          },
          {
            "type": "null"
          }
        ]
      },
      "payment_uri": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "terms": {
        "$ref": "#/components/schemas/QuoteTerms"
      },
      "treasury": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "client_reference_id",
      "amount",
      "currency",
      "chain_id",
      "asset",
      "amount_atomic",
      "exchange_rate",
      "address",
      "treasury",
      "payment_uri",
      "status",
      "expires_at",
      "created",
      "terms",
      "metadata"
    ],
    "type": "object"
  },
  "QuoteList": {
    "properties": {
      "data": {
        "items": {
          "$ref": "#/components/schemas/Quote"
        },
        "type": "array"
      },
      "has_more": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "list"
        ]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "object",
      "url",
      "has_more",
      "data"
    ],
    "type": "object"
  },
  "QuoteTerms": {
    "properties": {
      "confirmations": {
        "type": "string"
      },
      "max_deposit_atomic": {
        "type": "string"
      },
      "min_amount": {
        "minimum": 0,
        "type": "integer"
      },
      "min_deposit_atomic": {
        "type": "string"
      },
      "min_refund_atomic": {
        "type": "string"
      },
      "quote_amount_decimals": {
        "minimum": 0,
        "type": "integer"
      },
      "quote_spread_bps": {
        "minimum": 0,
        "type": "integer"
      },
      "quote_tolerance_bps": {
        "minimum": 0,
        "type": "integer"
      },
      "quote_ttl_seconds": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "quote_ttl_seconds",
      "quote_spread_bps",
      "quote_tolerance_bps",
      "quote_amount_decimals",
      "min_amount",
      "min_deposit_atomic",
      "max_deposit_atomic",
      "min_refund_atomic",
      "confirmations"
    ],
    "type": "object"
  },
  "QuoteView": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/Quote"
      },
      {
        "$ref": "#/components/schemas/ClientQuote"
      }
    ]
  },
  "Refund": {
    "properties": {
      "amount_atomic": {
        "type": "string"
      },
      "created": {
        "type": "integer"
      },
      "deposit": {
        "$ref": "#/components/schemas/ExpandableDeposit"
      },
      "destination_address": {
        "type": "string"
      },
      "failure_reason": {
        "type": [
          "string",
          "null"
        ]
      },
      "id": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "metadata": {
        "additionalProperties": {
          "type": "string"
        },
        "type": "object"
      },
      "object": {
        "type": "string",
        "enum": [
          "refund"
        ]
      },
      "receipt_log_index": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      },
      "status": {
        "type": "string"
      },
      "transaction_hash": {
        "type": [
          "string",
          "null"
        ]
      },
      "treasury": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "deposit",
      "amount_atomic",
      "destination_address",
      "treasury",
      "status",
      "created",
      "metadata"
    ],
    "type": "object"
  },
  "RefundList": {
    "properties": {
      "data": {
        "items": {
          "$ref": "#/components/schemas/Refund"
        },
        "type": "array"
      },
      "has_more": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "list"
        ]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "object",
      "url",
      "has_more",
      "data"
    ],
    "type": "object"
  },
  "ResendEventRequest": {
    "additionalProperties": false,
    "properties": {
      "webhook_endpoint": {
        "type": "string"
      }
    },
    "required": [
      "webhook_endpoint"
    ],
    "type": "object"
  },
  "RollApiKeyRequest": {
    "additionalProperties": false,
    "properties": {
      "expires_in": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "type": "object"
  },
  "RollWebhookKeyRequest": {
    "additionalProperties": false,
    "properties": {
      "expires_in": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "type": "object"
  },
  "Sweep": {
    "properties": {
      "address": {
        "type": "string"
      },
      "amount_atomic": {
        "type": "string"
      },
      "asset": {
        "type": [
          "string",
          "null"
        ]
      },
      "block_number": {
        "minimum": 0,
        "type": "integer"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "created": {
        "type": "integer"
      },
      "forwarder": {
        "type": "string"
      },
      "id": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "log_index": {
        "minimum": 0,
        "type": "integer"
      },
      "object": {
        "type": "string",
        "enum": [
          "sweep"
        ]
      },
      "token": {
        "type": "string"
      },
      "treasury": {
        "type": "string"
      },
      "tx_hash": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "chain_id",
      "forwarder",
      "address",
      "token",
      "treasury",
      "amount_atomic",
      "tx_hash",
      "log_index",
      "block_number",
      "created"
    ],
    "type": "object"
  },
  "SweepList": {
    "properties": {
      "data": {
        "items": {
          "$ref": "#/components/schemas/Sweep"
        },
        "type": "array"
      },
      "has_more": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "list"
        ]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "object",
      "url",
      "has_more",
      "data"
    ],
    "type": "object"
  },
  "Treasury": {
    "properties": {
      "address": {
        "type": "string"
      },
      "canceled_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "cancellation_reason": {
        "type": [
          "string",
          "null"
        ]
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "created": {
        "type": "integer"
      },
      "crediting_paused": {
        "type": "boolean"
      },
      "crediting_paused_by": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "effective_at": {
        "type": "integer"
      },
      "id": {
        "type": "string"
      },
      "kind": {
        "type": "string"
      },
      "livemode": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "treasury"
        ]
      },
      "replaced_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "status": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "chain_id",
      "address",
      "kind",
      "status",
      "effective_at",
      "created",
      "crediting_paused",
      "crediting_paused_by"
    ],
    "type": "object"
  },
  "TreasuryChallenge": {
    "properties": {
      "address": {
        "type": "string"
      },
      "chain_id": {
        "minimum": 0,
        "type": "integer"
      },
      "expires_at": {
        "type": "integer"
      },
      "livemode": {
        "type": "boolean"
      },
      "message": {
        "type": "string"
      },
      "nonce": {
        "type": "string"
      },
      "object": {
        "type": "string",
        "enum": [
          "treasury_challenge"
        ]
      }
    },
    "required": [
      "object",
      "livemode",
      "chain_id",
      "address",
      "nonce",
      "message",
      "expires_at"
    ],
    "type": "object"
  },
  "TreasuryList": {
    "properties": {
      "data": {
        "items": {
          "$ref": "#/components/schemas/Treasury"
        },
        "type": "array"
      },
      "has_more": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "list"
        ]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "object",
      "url",
      "has_more",
      "data"
    ],
    "type": "object"
  },
  "UpdateMetadataRequest": {
    "additionalProperties": false,
    "properties": {
      "metadata": {
        "$ref": "#/components/schemas/MetadataParam"
      }
    },
    "type": "object"
  },
  "UpdatePaymentSettingsRequest": {
    "additionalProperties": false,
    "properties": {
      "chains": {
        "items": {
          "$ref": "#/components/schemas/PaymentSettingsChain"
        },
        "type": [
          "array",
          "null"
        ]
      },
      "quote_creations_per_customer_per_minute": {
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      }
    },
    "type": "object"
  },
  "UpdateWebhookEndpointRequest": {
    "additionalProperties": false,
    "properties": {
      "description": {
        "type": [
          "string",
          "null"
        ]
      },
      "disabled": {
        "type": [
          "boolean",
          "null"
        ]
      },
      "enabled_events": {
        "items": {
          "type": "string"
        },
        "type": [
          "array",
          "null"
        ]
      },
      "metadata": {
        "$ref": "#/components/schemas/MetadataParam"
      },
      "url": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "type": "object"
  },
  "WebhookEndpointList": {
    "properties": {
      "data": {
        "items": {
          "$ref": "#/components/schemas/WebhookEndpointObject"
        },
        "type": "array"
      },
      "has_more": {
        "type": "boolean"
      },
      "object": {
        "type": "string",
        "enum": [
          "list"
        ]
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "object",
      "url",
      "has_more",
      "data"
    ],
    "type": "object"
  },
  "WebhookEndpointObject": {
    "properties": {
      "created": {
        "type": "integer"
      },
      "deleted": {
        "type": [
          "boolean",
          "null"
        ]
      },
      "description": {
        "type": [
          "string",
          "null"
        ]
      },
      "disabled_reason": {
        "type": [
          "string",
          "null"
        ]
      },
      "enabled_events": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "id": {
        "type": "string"
      },
      "last_attempt": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/DeliveryAttempt"
          },
          {
            "type": "null"
          }
        ]
      },
      "livemode": {
        "type": "boolean"
      },
      "metadata": {
        "additionalProperties": {
          "type": "string"
        },
        "type": "object"
      },
      "object": {
        "type": "string",
        "enum": [
          "webhook_endpoint"
        ]
      },
      "oldest_pending_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "pending_deliveries": {
        "type": "integer"
      },
      "status": {
        "type": "string"
      },
      "url": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "object",
      "livemode",
      "url",
      "enabled_events",
      "status",
      "metadata",
      "created",
      "pending_deliveries"
    ],
    "type": "object"
  },
  "WebhookKeyObject": {
    "properties": {
      "expires_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "public_key": {
        "type": "string"
      },
      "version": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "version",
      "public_key"
    ],
    "type": "object"
  },
  "WebhookKeyVersion": {
    "properties": {
      "expires_at": {
        "type": [
          "integer",
          "null"
        ]
      },
      "version": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "version"
    ],
    "type": "object"
  }
};
export const contracts: Record<string, Contract> = {
  "get_account": {
    "response": {
      "$ref": "#/components/schemas/AccountObject"
    }
  },
  "pause_account": {
    "response": {
      "$ref": "#/components/schemas/AccountObject"
    },
    "body": {
      "$ref": "#/components/schemas/AccountSelfPauseRequest"
    }
  },
  "resume_account": {
    "response": {
      "$ref": "#/components/schemas/AccountObject"
    },
    "body": {
      "$ref": "#/components/schemas/AccountSelfPauseRequest"
    }
  },
  "roll_webhook_key": {
    "response": {
      "$ref": "#/components/schemas/AccountObject"
    },
    "body": {
      "$ref": "#/components/schemas/RollWebhookKeyRequest"
    }
  },
  "list_api_keys": {
    "response": {
      "$ref": "#/components/schemas/ApiKeyList"
    }
  },
  "create_api_key": {
    "response": {
      "$ref": "#/components/schemas/ApiKeyObject"
    },
    "body": {
      "$ref": "#/components/schemas/CreateApiKeyRequest"
    }
  },
  "revoke_api_key": {
    "response": {
      "$ref": "#/components/schemas/ApiKeyObject"
    }
  },
  "get_api_key": {
    "response": {
      "$ref": "#/components/schemas/ApiKeyObject"
    }
  },
  "roll_api_key": {
    "response": {
      "$ref": "#/components/schemas/ApiKeyObject"
    },
    "body": {
      "$ref": "#/components/schemas/RollApiKeyRequest"
    }
  },
  "get_balance": {
    "response": {
      "$ref": "#/components/schemas/Balance"
    }
  },
  "get_config": {
    "response": {
      "$ref": "#/components/schemas/Config"
    }
  },
  "list_deposit_addresses": {
    "response": {
      "$ref": "#/components/schemas/DepositAddressList"
    }
  },
  "create_deposit_address": {
    "response": {
      "$ref": "#/components/schemas/DepositAddress"
    },
    "body": {
      "$ref": "#/components/schemas/CreateDepositAddressRequest"
    }
  },
  "get_deposit_address": {
    "response": {
      "$ref": "#/components/schemas/DepositAddressView"
    }
  },
  "update_deposit_address": {
    "response": {
      "$ref": "#/components/schemas/DepositAddress"
    },
    "body": {
      "$ref": "#/components/schemas/UpdateMetadataRequest"
    }
  },
  "rotate_deposit_address": {
    "response": {
      "$ref": "#/components/schemas/DepositAddress"
    }
  },
  "list_deposits": {
    "response": {
      "$ref": "#/components/schemas/DepositList"
    }
  },
  "get_deposit": {
    "response": {
      "$ref": "#/components/schemas/Deposit"
    }
  },
  "update_deposit": {
    "response": {
      "$ref": "#/components/schemas/Deposit"
    },
    "body": {
      "$ref": "#/components/schemas/UpdateMetadataRequest"
    }
  },
  "list_events": {
    "response": {
      "$ref": "#/components/schemas/EventList"
    }
  },
  "get_event": {
    "response": {
      "$ref": "#/components/schemas/EventObjectResponse"
    }
  },
  "resend_event": {
    "response": {
      "$ref": "#/components/schemas/EventObjectResponse"
    },
    "body": {
      "$ref": "#/components/schemas/ResendEventRequest"
    }
  },
  "list_forwarders": {
    "response": {
      "$ref": "#/components/schemas/ForwarderList"
    }
  },
  "get_payment_settings": {
    "response": {
      "$ref": "#/components/schemas/PaymentSettingsObject"
    }
  },
  "update_payment_settings": {
    "response": {
      "$ref": "#/components/schemas/PaymentSettingsObject"
    },
    "body": {
      "$ref": "#/components/schemas/UpdatePaymentSettingsRequest"
    }
  },
  "list_quotes": {
    "response": {
      "$ref": "#/components/schemas/QuoteList"
    }
  },
  "create_quote": {
    "response": {
      "$ref": "#/components/schemas/Quote"
    },
    "body": {
      "$ref": "#/components/schemas/CreateQuoteRequest"
    }
  },
  "get_quote": {
    "response": {
      "$ref": "#/components/schemas/QuoteView"
    }
  },
  "update_quote": {
    "response": {
      "$ref": "#/components/schemas/Quote"
    },
    "body": {
      "$ref": "#/components/schemas/UpdateMetadataRequest"
    }
  },
  "cancel_quote": {
    "response": {
      "$ref": "#/components/schemas/Quote"
    }
  },
  "list_refunds": {
    "response": {
      "$ref": "#/components/schemas/RefundList"
    }
  },
  "create_refund": {
    "response": {
      "$ref": "#/components/schemas/Refund"
    },
    "body": {
      "$ref": "#/components/schemas/CreateRefundRequest"
    }
  },
  "get_refund": {
    "response": {
      "$ref": "#/components/schemas/Refund"
    }
  },
  "update_refund": {
    "response": {
      "$ref": "#/components/schemas/Refund"
    },
    "body": {
      "$ref": "#/components/schemas/UpdateMetadataRequest"
    }
  },
  "cancel_refund": {
    "response": {
      "$ref": "#/components/schemas/Refund"
    }
  },
  "mark_refund_paid": {
    "response": {
      "$ref": "#/components/schemas/Refund"
    },
    "body": {
      "$ref": "#/components/schemas/MarkRefundPaidRequest"
    }
  },
  "list_sweeps": {
    "response": {
      "$ref": "#/components/schemas/SweepList"
    }
  },
  "list_treasuries": {
    "response": {
      "$ref": "#/components/schemas/TreasuryList"
    }
  },
  "create_treasury": {
    "response": {
      "$ref": "#/components/schemas/Treasury"
    },
    "body": {
      "$ref": "#/components/schemas/CreateTreasuryRequest"
    }
  },
  "create_treasury_challenge": {
    "response": {
      "$ref": "#/components/schemas/TreasuryChallenge"
    },
    "body": {
      "$ref": "#/components/schemas/CreateTreasuryChallengeRequest"
    }
  },
  "get_treasury": {
    "response": {
      "$ref": "#/components/schemas/Treasury"
    }
  },
  "cancel_treasury": {
    "response": {
      "$ref": "#/components/schemas/Treasury"
    }
  },
  "pause_treasury": {
    "response": {
      "$ref": "#/components/schemas/Treasury"
    }
  },
  "resume_treasury": {
    "response": {
      "$ref": "#/components/schemas/Treasury"
    }
  },
  "list_webhook_endpoints": {
    "response": {
      "$ref": "#/components/schemas/WebhookEndpointList"
    }
  },
  "create_webhook_endpoint": {
    "response": {
      "$ref": "#/components/schemas/WebhookEndpointObject"
    },
    "body": {
      "$ref": "#/components/schemas/CreateWebhookEndpointRequest"
    }
  },
  "delete_webhook_endpoint": {
    "response": {
      "$ref": "#/components/schemas/DeletedWebhookEndpoint"
    }
  },
  "get_webhook_endpoint": {
    "response": {
      "$ref": "#/components/schemas/WebhookEndpointObject"
    }
  },
  "update_webhook_endpoint": {
    "response": {
      "$ref": "#/components/schemas/WebhookEndpointObject"
    },
    "body": {
      "$ref": "#/components/schemas/UpdateWebhookEndpointRequest"
    }
  },
  "test_webhook_endpoint": {
    "response": {
      "$ref": "#/components/schemas/EventObjectResponse"
    }
  }
};
